#!/bin/sh
# detect git push -f
force=0
while read -r old new ref; do
        hasrevs=$(git rev-list "$old" "^$new" | sed 1q)
        if test -n "$hasrevs"; then
                force=1
                break
        fi
done

# Update nginx server on: /var/www/
stagit-update /var/www/

